// ─── DATA ───────────────────────────────────────────────────────────────────

// Cloudinary delivery helper: injects format/quality/width transforms into an upload URL.
export const cld = (url, w) => url.replace("/upload/", `/upload/f_auto,q_auto,w_${w}/`);

export const SKILL_GROUPS = [
  {
    id: "code", icon: "{ }", name: "Code & Development", sub: "More than 6 years",
    skills: [
      { icon: "⚡", name: "JavaScript", pct: 82 },
      { icon: "🐘", name: "PHP", pct: 78 },
      { icon: "🐍", name: "Python", pct: 68 },
      { icon: "🟢", name: "Node.js", pct: 72 },
      { icon: "🔴", name: "Laravel", pct: 80 },
      { icon: "⚛️", name: "React JS", pct: 85 },
      { icon: "▲", name: "Next.js", pct: 78 },
      { icon: "🌊", name: "Tailwind CSS", pct: 87 },
    ],
  },
  {
    id: "design", icon: "✦", name: "Design & Creative", sub: "More than 5 years",
    skills: [
      { icon: "✏️", name: "Figma", pct: 88 },
      { icon: "🖌️", name: "Illustrator", pct: 82 },
      { icon: "🖼️", name: "Photoshop", pct: 80 },
      { icon: "📐", name: "SketchUp", pct: 65 },
      { icon: "🎨", name: "Canva", pct: 92 },
    ],
  },
  {
    id: "seo", icon: "↗", name: "SEO & Marketing", sub: "More than 4 years",
    skills: [
      { icon: "📈", name: "Google Ads", pct: 85 },
      { icon: "📘", name: "Meta Pixel", pct: 80 },
      { icon: "📊", name: "Google Analytics", pct: 90 },
      { icon: "🔍", name: "Search Console", pct: 88 },
      { icon: "🔗", name: "Ahrefs", pct: 80 },
      { icon: "📱", name: "Social Media", pct: 85 },
    ],
  },
  {
    id: "cloud", icon: "☁", name: "Cloud & Infrastructure", sub: "More than 3 years",
    skills: [
      { icon: "🌩️", name: "Cloudflare", pct: 85 },
      { icon: "🔥", name: "Firebase", pct: 75 },
      { icon: "🔵", name: "DigitalOcean", pct: 80 },
      { icon: "🖼️", name: "Cloudinary", pct: 75 },
      { icon: "🛡️", name: "Nginx", pct: 76 },
      { icon: "🐧", name: "Linux", pct: 78 },
      { icon: "🐙", name: "Git", pct: 82 },
    ],
  },
];

export const PORTFOLIO_ITEMS = [
  {
    id: 1, featured: true,
    bg: "linear-gradient(135deg, #3b82f6, #1e3a8a)",
    img: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777564895/Screenshot11_i4ukyg.png",
    alt: "Whitebox.asia",
    tags: ["Cloud Infra", "Web Perf", "SEO"],
    title: "Whitebox.asia",
    desc: "A specialist platform focusing on high-performance websites, SEO optimization, and secure, scalable cloud infrastructure management.",
    link: "https://whitebox.asia",
  },
  {
    id: 2,
    bg: "linear-gradient(135deg, #f59e0b, #92400e)",
    img: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777564896/Screenshot10_gvajvn.png",
    alt: "Bali Sunday Tour",
    tags: ["Web Design", "Travel & Tour"],
    title: "Bali Sunday Tour",
    desc: "A premium travel platform offering luxury tours to experience hidden treasures and new adventures across Bali.",
    link: "https://balisundaytour.com",
  },
  {
    id: 3,
    bg: "linear-gradient(135deg, #1e3a8a, #16a34a)",
    img: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777564893/Screenshot8_dpggsk.png",
    alt: "Flower Pool Bali",
    tags: ["Web Design", "Booking System"],
    title: "Flower Pool Bali",
    desc: "An elegant service booking platform offering custom flower pools, villa decorations, and surprise proposal setups in Bali.",
    link: "https://flowerpoolbali.com",
  },
  {
    id: 4,
    bg: "linear-gradient(135deg, #f97316, #ea580c)",
    img: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777564902/portfolio6_bltawa.png",
    alt: "React Movie",
    tags: ["React JS", "API"],
    title: "React Movie",
    desc: "Film website built with React JS using a third-party movie API.",
    link: "#",
  },
  {
    id: 5,
    bg: "linear-gradient(135deg, #f59e0b, #d97706)",
    img: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777564895/portfolio2_jeezyp.png",
    alt: "Malang Strudel",
    tags: ["Web Design"],
    title: "Malang Strudel",
    desc: "Creation of the Abimanyu Strudel brand website.",
    link: "#",
  },
  {
    id: 6,
    bg: "linear-gradient(135deg, #6366f1, #4f46e5)",
    img: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777564907/portfolio3_em9eii.png",
    alt: "Personal Blog",
    tags: ["Materialize CSS"],
    title: "Personal Blog",
    desc: "Personal website built with Materialize CSS framework.",
    link: "#",
  },
  {
    id: 7, hidden: true,
    bg: "linear-gradient(135deg, #22c55e, #16a34a)",
    img: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777564897/portfolio1_nc29f0.png",
    alt: "Malang News",
    tags: ["WordPress", "SEO"],
    title: "Malang News",
    desc: "A comprehensive news website dedicated to covering stories about the city of Malang.",
    link: "#",
  },
  {
    id: 8, hidden: true,
    bg: "linear-gradient(135deg, #14b8a6, #0f766e)",
    img: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777564904/portfolio5_wn0hpj.png",
    alt: "PSHT Singosari",
    tags: ["Laravel"],
    title: "PSHT Singosari",
    desc: "Organization website built using the Laravel framework.",
    link: "#",
  },
  {
    id: 9, hidden: true,
    bg: "linear-gradient(135deg, #ec4899, #be185d)",
    img: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777564894/portfolio4_xyeysz.png",
    alt: "Beautiful News",
    tags: ["WordPress"],
    title: "Beautiful News",
    desc: "Simple elegant news website using WordPress.",
    link: "#",
  },
  {
    id: 10, hidden: true,
    bg: "linear-gradient(135deg, #8b5cf6, #7c3aed)",
    img: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777564905/portfolio9_tz6cbp.png",
    alt: "PSHT Data Management",
    tags: ["Laravel", "Web App"],
    title: "PSHT Data Management",
    desc: "Data storage and management web application built on Laravel.",
    link: "#",
  },
  {
    id: 11, hidden: true,
    bg: "linear-gradient(135deg, #0ea5e9, #0284c7)",
    img: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777564910/portfolio8_kb51cu.png",
    alt: "Barenlitbang Info System",
    tags: ["Government", "Web App"],
    title: "Barenlitbang Info System",
    desc: "Malang City Information System for the Barenlitbang department.",
    link: "#",
  },
];

export const CLIENTS = [
  { src: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777565627/abimanyu_qipuf7.png", alt: "Abimanyu Travel" },
  { src: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777565628/abimanyukoi_jkkge3.png", alt: "Abimanyu Koi" },
  { src: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777565630/pertamina_a3zmnz.png", alt: "Pertamina" },
  { src: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777565634/wikawh_empdg6.png", alt: "Wika Water Heater" },
  { src: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777565628/beautiful_tzbfaj.png", alt: "Beautiful Malang" },
  { src: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777565631/Seohost_medrir.png", alt: "SEO Webhosting" },
  { src: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777565631/lambda_v4mrl1.png", alt: "Lambda Consulting" },
  { src: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777565633/matahari_q8bifi.png", alt: "Meubel Matahari" },
  { src: "https://res.cloudinary.com/dmis60dxy/image/upload/v1777565634/suryabaru_juvm88.png", alt: "CV Surya Baru" },
];
